language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t nmanojkumar030/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true nmanojkumar030/docker-react npm run test